### ISSUE TITLE
Outdated ?

### ISSUE THREAD

**Issue by Merichbier** [MicrosoftDocs/mesh-docs#11]
Just following this page doesn't work. We get stuck on the login screen and always getting "Failed to connect to server".

Either there is an issue on our side, or the documentation is missing info :
- Does it work with Private account ? (According to the docs, yes as there is no mention of it :) ) We thought no we need work account
- What services does the work account have for mesh app to work ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8102ff1b-1dac-6b6e-f876-e692a98df4c5
* Version Independent ID: 3d66a202-47cc-c7cb-0bc0-5c914581afe3
* Content: [Get started with Microsoft Mesh (Preview)](https://learn.microsoft.com/en-us/mesh/get-started)
* Content Source: [mesh/get-started.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/get-started.md)
* Product: **mixed-reality**
* GitHub Login: @qianw211
* Microsoft Alias: **qianwen**

**Comment by ima49** [comment]
I'm stucked with the same problem; all permission provided

**Comment by Merichbier** [comment]
Actually after some research we fall upon this forum thread : https://techcommunity.microsoft.com/t5/mixed-reality-feedback-and-help/mesh-app-not-working/m-p/3734583
The issue is on Microsoft side (we confirmed this with a intern contact.)
I wish there was some communication and had not loose a half day trying to fix something which has no need to be fixed on our side.....
