### ISSUE TITLE
Overview page suggests moving to "Choosing your Journey", bypassing "Prerequisites"

### ISSUE THREAD

**Issue by paco-ms** [MicrosoftDocs/mesh-docs#14]
[Enter feedback here]

Overview page "next" button (at the end of the page) leads to "Choosing your Journey" and skips "Prerequisites"

I'd assume we'd want users to get those prerequisites first.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06ff6eac-f9bf-d190-7831-f4c35b09feab
* Version Independent ID: 06ff6eac-f9bf-d190-7831-f4c35b09feab
* Content: [Mesh Development overview](https://learn.microsoft.com/en-gb/mesh/develop/development-overview)
* Content Source: [mesh/develop/development-overview.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/develop/development-overview.md)
* Product: **mesh**
* GitHub Login: @typride
* Microsoft Alias: **vinnietieto**

**Comment by vtieto** [comment]
Fixed.
