### ISSUE TITLE
Instructions use the present tense, but they describe what we want to achieve, not the current state

### ISSUE THREAD

**Issue by paco-ms** [MicrosoftDocs/mesh-docs#16]
[Enter feedback here]
The text "_When the scene starts, the video screen displays a still image (due to VideoStill being active) and does not play a video (which is due to Video being inactive). When the participant presses the Play/Stop button (which shows "Play"), it makes Video active, which causes the video to play, and simultaneously makes VideoStill inactive, which hides the still image. When the participant presses the button again (which now shows "Stop"), Video is made inactive, stopping the video, and VideoStill is made active again, which makes the video screen display the still image._"

Seems to describe the present state ("_causes the video to play_", etc..), but it really should be describing what we want to achieve ("we want it to play the video") since we haven't wired up the logic yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17c45323-db79-3431-bc5d-d453d02d8d71
* Version Independent ID: 17c45323-db79-3431-bc5d-d453d02d8d71
* Content: [Mesh 101 Add interactivity with Mesh Visual Scripting](https://learn.microsoft.com/en-gb/mesh/develop/getting-started/mesh-101-tutorial/mesh-101-03-visual-scripting)
* Content Source: [mesh/develop/getting-started/mesh-101-tutorial/mesh-101-03-visual-scripting.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/develop/getting-started/mesh-101-tutorial/mesh-101-03-visual-scripting.md)
* GitHub Login: @typride
* Microsoft Alias: **vinnietieto**

**Comment by vtieto** [comment]
This is okay. Comments like "When the scene starts" and "when the button is clicked" sets the actions in the correct timeframe.
