### ISSUE TITLE
 Microsoft Mesh App

### ISSUE THREAD

**Issue by wang526** [MicrosoftDocs/mesh-docs#2]
[在此处输入反馈]
Microsoft Mesh可以将一个应用程序添加到空间中吗, 因为打开应用程序后,需要多人进行协作对模型进行操作,模型需要通过应用程序才能加载出来,因为模型是动态从服务器加载的

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: abac5e1b-1adb-5236-0474-d20cbdefe359
* Version Independent ID: 9cbbb2e8-f88e-87b0-638b-3fe6257ec231
* Content: [Microsoft Mesh 应用（预览版）入门](https://docs.microsoft.com/zh-cn/mesh/mesh-app/)
* Content Source: [mesh/mesh-app/index.md](https://github.com/MicrosoftDocs/mesh-docs-pr.zh-cn/blob/live/mesh/mesh-app/index.md)
* Product: **mixed-reality**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by qianw211** [comment]
Hi @wang526, 您好！ 是否可以明确一下您需要将什么样的应用程序添加到空间中呢？目前能够添加到空间的文件只有3维模型的 .glb 文件。谢谢！

**Comment by qianw211** [comment]
#please-close if there're no additional questions. Thanks!
