### ISSUE TITLE
Wrong last image?

### ISSUE THREAD

**Issue by kaipiroska** [MicrosoftDocs/mesh-docs#22]
Hello,

it seems that the last image is the same as the previous and it is not matching the text before it: "When unsure if a setting is enabled or disabled for a platform you are developing for, reference the URP assets contained within the Mesh Toolkit Uploader's URP folder".

Thanks,
Pekka Kaipiainen

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd327c11-3ea7-2f39-bea1-8bd669ef8e21
* Version Independent ID: dd327c11-3ea7-2f39-bea1-8bd669ef8e21
* Content: [Model textures](https://learn.microsoft.com/en-us/mesh/develop/design/model-textures)
* Content Source: [mesh/develop/design/model-textures.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/develop/design/model-textures.md)
* Service: **mesh**
* GitHub Login: @typride
* Microsoft Alias: **vinnietieto**

**Comment by vtieto** [comment]
I inserted the correct image.
