### ISSUE TITLE
Wrong image

### ISSUE THREAD

**Issue by kaipiroska** [MicrosoftDocs/mesh-docs#25]
Hi,

wrong image (about lightmap settings instead of troubleshooting) also on the last page. 

Thanks,
Pekka Kaipiainen

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1f68f92-3766-eac9-3b1b-2c21e5100551
* Version Independent ID: f1f68f92-3766-eac9-3b1b-2c21e5100551
* Content: [Design - lighting concepts](https://learn.microsoft.com/en-us/mesh/develop/design/lighting)
* Content Source: [mesh/develop/design/lighting.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/develop/design/lighting.md)
* Service: **mesh**
* GitHub Login: @typride
* Microsoft Alias: **vinnietieto**

**Comment by vtieto** [comment]
I updated the Lighting page.
