### ISSUE TITLE
License requirement section has incorrect text for link

### ISSUE THREAD

**Issue by CathyMoya** [MicrosoftDocs/mesh-docs#27]
The link at the bottom of the license requirements section says something about M365 setup, but it doesn't match the title of the actual page you go to

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c75457f7-3932-771c-9d2f-4387ec50b92f
* Version Independent ID: c75457f7-3932-771c-9d2f-4387ec50b92f
* Content: [Prerequsites for Mesh development](https://learn.microsoft.com/en-us/mesh/develop/getting-started/prerequisites)
* Content Source: [mesh/develop/getting-started/prerequisites.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/develop/getting-started/prerequisites.md)
* Service: **mesh**
* GitHub Login: @typride
* Microsoft Alias: **vinnietieto**

**Comment by vtieto** [comment]
Fixed.

https://github.com/MicrosoftDocs/mesh-docs-pr/pull/476

**Comment by vtieto** [comment]
Fixed. 

https://github.com/MicrosoftDocs/mesh-docs-pr/pull/476
