### ISSUE TITLE
sentence is confusing - 30 minutes in advance, yes or no? 

### ISSUE THREAD

**Issue by CathyMoya** [MicrosoftDocs/mesh-docs#28]
This sentence is confusing
"Events should not be longer than 3 hours and scheduled more than 30 minutes in advance."
I think this should say "Events should not be longer than 3 hours and events should be scheduled more than 30 minutes in advance." but the way it is now I could read that as "Events should not be longer than 3 hours and should NOT be scheduled more than 30 minutes in advance."
And really the 30 minutes in advance only matters if you want to customize, right? And for a first time, 30 minutes is not NEARLY enough time to customize something, they will be floundering  :-p

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dbb55180-6908-03f1-f45b-8d176d79bf3b
* Version Independent ID: dbb55180-6908-03f1-f45b-8d176d79bf3b
* Content: [Create event in Mesh portal](https://learn.microsoft.com/en-us/mesh/events-guide/create-event-mesh-portal)
* Content Source: [mesh/events-guide/create-event-mesh-portal.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/events-guide/create-event-mesh-portal.md)
* Service: **mesh**
* GitHub Login: @typride
* Microsoft Alias: **tmilligan**

**Comment by Sean-Kerawala** [comment]
fixed
