### ISSUE TITLE
Creating a Template step should have you select the world first

### ISSUE THREAD

**Issue by CathyMoya** [MicrosoftDocs/mesh-docs#29]
On this step 
"Select create new template and add your Title, Description, and select the World location for the template to exist in."
the problem is you can't change the world location when you are creating a template, you have to change it on the dashboard screen first before you go into that dialog box. So the step should have them first set the world, then click Create event template

also, step 3 doesn't have a picture and Tanisha got confused :-( 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 704b8aef-7454-d9ee-c41c-398c9d887776
* Version Independent ID: 704b8aef-7454-d9ee-c41c-398c9d887776
* Content: [Create event template in Microsoft Mesh](https://learn.microsoft.com/en-us/mesh/events-guide/create-template)
* Content Source: [mesh/events-guide/create-template.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/events-guide/create-template.md)
* Service: **mesh**
* GitHub Login: @typride
* Microsoft Alias: **tmilligan**

**Comment by Sean-Kerawala** [comment]
Resolved!
