### ISSUE TITLE
 I an using Microsoft Mesh App on Hololens2. When I was dragging my model form OneDrive to my space in this app, it failed and showed "this model is too complex". Why is this problem? Is my model too big, or this model has too much triangle pieces? Is there a limitition about models which can be draged in from OneDrive?

### ISSUE THREAD

**Issue by puzzle008** [MicrosoftDocs/mesh-docs#3]
[在此处输入反馈]

 I an using Microsoft Mesh App on Hololens2. When I was dragging my model form OneDrive to my space in this app, it failed and showed "this model is too complex". Why is this problem? Is my model too big, or this model has too much triangle pieces? Is there a limitition about models which can be draged in from OneDrive?
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ee184115-3c90-5e6e-65fa-2e4f2cc96556
* Version Independent ID: cfef9a02-1678-381d-8e43-fc2107713179
* Content: [Microsoft 网状应用 (预览) 常见问题](https://docs.microsoft.com/zh-cn/mesh/mesh-app/faq)
* Content Source: [mesh/mesh-app/faq.md](https://github.com/MicrosoftDocs/mesh-docs-pr.zh-cn/blob/live/mesh/mesh-app/faq.md)
* Product: **mixed-reality**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by qianw211** [comment]
Hi @puzzle008, we currently have a per file size limit of 75MB, or 300,000 vertex count for user content.  If these limits are exceeded, you will get a warning like the above.  To resolve this, you can try out the ARR feature in Mesh App, where more complex models can be loaded into the space: https://docs.microsoft.com/en-us/mesh/mesh-app/arr-content.

We appreciate your feedback, thank you!

**Comment by qianw211** [comment]
#please-close, a warning has been added to the docs: 
https://docs.microsoft.com/en-us/mesh/mesh-app/import-content#import-user-content
