### ISSUE TITLE
Hand raise shouldn't be in PuP

### ISSUE THREAD

**Issue by CathyMoya** [MicrosoftDocs/mesh-docs#34]
the pictures in the Mesh controls overview and the Adjust settings section has the raise hand button, but hand raise did not make it to public preview. It's not even in private preview yet, just internal builds

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 897f9bc6-c71b-e7cb-f936-8cbd53525732
* Version Independent ID: 897f9bc6-c71b-e7cb-f936-8cbd53525732
* Content: [Mesh user controls](https://learn.microsoft.com/en-us/mesh/user-guide/mesh-user-controls)
* Content Source: [mesh/user-guide/mesh-user-controls.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/user-guide/mesh-user-controls.md)
* Service: **mesh**
* GitHub Login: @qianw211
* Microsoft Alias: **qianwen**

**Comment by qianw211** [comment]
Hi @CathyMoya, I removed any images with the hand raise button for now! Will add it back in once hand raise is available in public release. Thanks!
