### ISSUE TITLE
 Local Scene Scope - confusing

### ISSUE THREAD

**Issue by sabingeorgehlx** [MicrosoftDocs/mesh-docs#36]
"To exclude parts of your scene from this automatic sharing, add a Local Scene Scope component. Everything underneath that transform won't be shared automatically."

This section Local Scene Scope means "**Local Script Scope**".   I tried with Local Script Scope, but still it tracks, states like game object's active state, transform position, rotation, scale. Also animators also synced.

How to make Visual Script fully local? for example playing animation using animator. With current SDK, if you trigger animator, it executes on every client even if it is under Local Script Scope. 

What I am looking for a complete non shared hierarchy, meant only for local user.  Example, a notification when he clicks on something that only visible to him not to other users.

Could you please include this? how to achieve this.  

Meshtoolkit version 5.2312.0
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc488396-357f-3440-a76c-467c13a189d1
* Version Independent ID: dc488396-357f-3440-a76c-467c13a189d1
* Content: [Mesh Visual Scripting programmer's guide](https://learn.microsoft.com/en-us/mesh/develop/script-your-scene-logic/visual-scripting/visual-scripting-programmers-guide)
* Content Source: [mesh/develop/script-your-scene-logic/visual-scripting/visual-scripting-programmers-guide.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/develop/script-your-scene-logic/visual-scripting/visual-scripting-programmers-guide.md)
* Service: **mesh**
* GitHub Login: @typride
* Microsoft Alias: **vinnietieto**

**Comment by vtieto** [comment]
I updated the Visual Scripting Programmer's Article to include information on how to keep a visual script fully local.
