### ISSUE TITLE
Contact button for DXC Technology doesnt seem to work on PC

### ISSUE THREAD

**Issue by cmatthews3** [MicrosoftDocs/mesh-docs#38]
When I click the contact button for DXC technology on PC(using Google Chrome), nothing seems to happen.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6875e273-50d5-21be-7c5f-b278ecba311a
* Version Independent ID: 6875e273-50d5-21be-7c5f-b278ecba311a
* Content: [Meet our Mesh Early Adopters - Microsoft Mesh](https://learn.microsoft.com/en-us/mesh/develop/mesh-tap-participants)
* Content Source: [mesh/develop/mesh-tap-participants.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/develop/mesh-tap-participants.md)
* Service: **mesh**
* GitHub Login: @typride
* Microsoft Alias: **tmilligan**

**Comment by typride** [comment]
This was resolved. Thank you!
