### ISSUE TITLE
Desktop syncing is a pretty advanced feature

### ISSUE THREAD

**Issue by tmlyon** [MicrosoftDocs/mesh-docs#4]
The article kind of implies that you need to set up desktop syncing for the onedrive folder, which is not the case. That's a more advanced feature that is kind of beside the point to get started, and it seems like should be treated as such in the docs rather than in the mainline how-to. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba72ca69-1987-70e2-4f60-afca2c637dd1
* Version Independent ID: 9e3478af-4479-e700-7772-2fc5aa566cfd
* Content: [Use the Mesh app](https://docs.microsoft.com/en-us/mesh/mesh-app/use-mesh)
* Content Source: [mesh/mesh-app/use-mesh.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/mesh-app/use-mesh.md)
* Product: **mixed-reality**
* GitHub Login: @qianw211
* Microsoft Alias: **v-qianwen**

**Comment by qianw211** [comment]
Hi @jbienzms, what do you think of @tmlyon's comment above? Thanks!

**Comment by jbienzms** [comment]
Thanks for asking @qianw211. I agree that desktop sync isn't _required_.  So far our team has seen about 50% of people using desktop sync and 50% using OneDrive web. The main reason the article suggests against OneDrive web is thinking down the road to large file support. The web interface is fine for small models and documents, but Mesh App already has preliminary support for Azure Remote Rendering models. As file sizes get large, desktop synchronization becomes beneficial for handling background upload, retries, etc. But we could tone down the language that suggests against using the web interface. Or we could add verbiage that helps explain the scenarios where desktop sync can be helpful.

**Comment by qianw211** [comment]
Thanks, @jbienzms!  I'll update the docs.

**Comment by qianw211** [comment]
The following text has been added to MeshDocs to reflect the above:

Now you can access the Apps > Microsoft Mesh app (Preview) > MyContent folder on your desktop and start adding your content for the Mesh app. Desktop synchronization is beneficial for handling large file sizes and complex 3D models. Alternatively if your content is small and not complex, you can also use OneDrive web.

**Comment by qianw211** [comment]
#please-close
