### ISSUE TITLE
Video URLs not working on the Template edit

### ISSUE THREAD

**Issue by leeprobert** [MicrosoftDocs/mesh-docs#40]
I have not been able to add a video URL without the error that I don't have permissions. I have tried lots of different publicly available video URLs including this one: https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

What are the rules for adding video content? Does it have to be a live stream? A specific codec?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dadd3b69-7a3f-5ba6-890b-10f555f80f6e
* Version Independent ID: dadd3b69-7a3f-5ba6-890b-10f555f80f6e
* Content: [Produce event in Mesh - Microsoft Mesh](https://learn.microsoft.com/en-us/mesh/events-guide/produce-event)
* Content Source: [mesh/events-guide/produce-event.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/events-guide/produce-event.md)
* Service: **mesh**
* GitHub Login: @typride
* Microsoft Alias: **tmilligan**

**Comment by ltwlf** [comment]
Currently only SharePoint/OneDrive links are working. Either this is an issue in the documentation or a bug.

**Comment by leeprobert** [comment]
Hey! Yea, this is not really a documentation bug. I am noticing quite a few issues that I would love to report with the developers. If there is a channel for this let me know.

**Comment by typride** [comment]
So, after speaking with the team, it seems like that video link should work. Do you mind filing feedback in the Mesh application?

**Comment by typride** [comment]
That way, we can track the bug and work to fix it. Apologies for any inconvenience this may have caused.

**Comment by typride** [comment]
@leeprobert any chance you could try and play the video anyway even if you are getting an error for permissions? We suspect that the error may not be blocking. We are actively investigating this and appreciate your help. Thank you!
