### ISSUE TITLE
Outdated template image

### ISSUE THREAD

**Issue by kaipiroska** [MicrosoftDocs/mesh-docs#44]
In Unity 2022.3.15f this is the correct template for 3D URP projects:

![image](https://github.com/MicrosoftDocs/mesh-docs/assets/141272609/f481786d-b9e2-4718-8724-cc5a818d24fd)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fadb6331-4570-1c97-fbc2-c3219057b02a
* Version Independent ID: fadb6331-4570-1c97-fbc2-c3219057b02a
* Content: [Create a new project or update an existing one - Microsoft Mesh](https://learn.microsoft.com/en-us/mesh/develop/build-your-basic-environment/create-a-new-project-or-update)
* Content Source: [mesh/develop/build-your-basic-environment/create-a-new-project-or-update.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/develop/build-your-basic-environment/create-a-new-project-or-update.md)
* Service: **mesh**
* GitHub Login: @typride
* Microsoft Alias: **vinnietieto**

**Comment by Sean-Kerawala** [comment]
Thank you! Docs are updated.
