### ISSUE TITLE
Sign out FAQ

### ISSUE THREAD

**Issue by tmlyon** [MicrosoftDocs/mesh-docs#5]
There was a customer question about how to sign out of the app that we should consider adding here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba72ca69-1987-70e2-4f60-afca2c637dd1
* Version Independent ID: 9e3478af-4479-e700-7772-2fc5aa566cfd
* Content: [Use the Mesh app](https://docs.microsoft.com/en-us/mesh/mesh-app/use-mesh)
* Content Source: [mesh/mesh-app/use-mesh.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/mesh-app/use-mesh.md)
* Product: **mixed-reality**
* GitHub Login: @qianw211
* Microsoft Alias: **v-qianwen**

**Comment by amjackso** [comment]
If the _Menu_ is not already displayed, hold up your hand with your palm facing towards you (and in view of the HoloLens) to bring up the _Hand Menu_, and click _Menu_ at the top of the _Hand Menu_. Once the _Hand Menu_ is open, click the _Settings_ icon, click _Sign Out_ in the bottom right corner of the _Menu_, and then, click _Yes_.

**Comment by qianw211** [comment]
#please-close
